### ISSUE TITLE
Question about FrozenBatchNorm in Semantic Segmentation

### ISSUE THREAD

**Issue by zzzqzhou** [lixiaotong97/DSU#7]
Hi, author. Thanks for open-sourcing the code.

I have a question about the FrozenBatchNorm in semantic segmentation.  I have read about the code of FrozenBatchNorm2d you provided. It seems that the FrozenBatchNorm2d is an identity operation. Which means that there is no normalization operation during training. Why you use FrozenBatchNorm during training in semantic segmentation?

**Comment by lixiaotong97** [comment]
Hi, thanks for your question. 
The implementation is from the original semantic segmentation FADA repo[https://github.com/JDAI-CV/FADA], which we do not change for a fair comparison.
